apiVersion: v2
appVersion: 1.4.0
description: A Kubernetes controller that spawns a notebook for a user
home: https://github.com/kubeflow/kubeflow/tree/master/components/notebook-controller
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: notebook-controller
sources:
  - https://github.com/kubeflow/kubeflow/tree/master/components/notebook-controller
  - https://github.com/cowboysysop/charts/tree/master/charts/notebook-controller
version: 1.2.0
dependencies:
  - name: common
    version: 1.17.1
    repository: https://charts.bitnami.com/bitnami/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=1.19"
