apiVersion: v2
appVersion: 0.2.1
description: Get up and running with large language models, locally
home: https://ollama.com/
icon: https://raw.githubusercontent.com/cowboysysop/charts/master/charts/ollama/icon.png
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: ollama
sources:
  - https://github.com/ollama/ollama
  - https://github.com/cowboysysop/charts/tree/master/charts/ollama
version: 1.2.1
dependencies:
  - name: common
    version: 2.20.3
    repository: https://charts.bitnami.com/bitnami/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=1.24"
