apiVersion: v2
appVersion: 1.0.0
description: Set of components that automatically adjust the amount of CPU and memory requested by pods running in the Kubernetes Cluster
home: https://github.com/kubernetes/autoscaler
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: vertical-pod-autoscaler
sources:
  - https://github.com/kubernetes/autoscaler
  - https://github.com/cowboysysop/charts/tree/master/charts/vertical-pod-autoscaler
version: 9.5.0
dependencies:
  - name: common
    version: 2.13.3
    repository: https://charts.bitnami.com/bitnami/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=1.24"
