apiVersion: v1
appVersion: 0.8.0
description: Set of components that automatically adjust the amount of CPU and memory requested by pods running in the Kubernetes Cluster
home: https://github.com/kubernetes/autoscaler
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: vertical-pod-autoscaler
version: 1.4.3
