apiVersion: v2
appVersion: 1.10.1
description: Tiny Go webserver that prints os information and HTTP request to output
home: https://github.com/traefik/whoami
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: whoami
sources:
  - https://github.com/traefik/whoami
  - https://github.com/cowboysysop/charts/tree/master/charts/whoami
version: 5.1.0
dependencies:
  - name: common
    version: 2.9.0
    repository: https://charts.bitnami.com/bitnami/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=1.24"
