apiVersion: v2
appVersion: 0.8.1
description: Enables running a server to display Lighthouse CI results
home: https://github.com/GoogleChrome/lighthouse-ci
icon: https://raw.githubusercontent.com/GoogleChrome/lighthouse-ci/master/packages/server/src/ui/logo.svg
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: lighthouse-ci
sources:
  - https://github.com/GoogleChrome/lighthouse-ci
  - https://github.com/cowboysysop/charts/tree/master/charts/lighthouse-ci
version: 7.5.0
dependencies:
  - name: common
    version: 2.9.0
    repository: https://charts.bitnami.com/bitnami/
  - name: mariadb
    version: 11.5.7
    repository: https://charts.bitnami.com/bitnami/
    condition: mariadb.enabled
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=1.24"
