apiVersion: v2
appVersion: 0.12.0
description: A Kubernetes-native project for automated machine learning
home: https://github.com/kubeflow/katib
icon: https://raw.githubusercontent.com/kubeflow/katib/master/docs/images/logo.svg
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: katib
sources:
  - https://github.com/kubeflow/katib
  - https://github.com/cowboysysop/charts/tree/master/charts/katib
version: 2.3.6
dependencies:
  - name: common
    version: 1.16.1
    repository: https://charts.bitnami.com/bitnami/
  - name: mariadb
    version: 11.4.7
    repository: https://charts.bitnami.com/bitnami/
    condition: mariadb.enabled
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=1.19"
