# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Database
  licenses: Apache-2.0
  images: |
    - name: os-shell
      image: docker.io/bitnamilegacy/os-shell:12-debian-12-r22
    - name: postgres-exporter
      image: docker.io/bitnamilegacy/postgres-exporter:0.15.0-debian-12-r33
    - name: postgresql
      image: docker.io/bitnamilegacy/postgresql:16.3.0-debian-12-r14
apiVersion: v2
appVersion: 16.3.0
dependencies:
- name: common
  repository: oci://ghcr.io/cowboysysop/charts
  tags:
  - bitnami-common
  version: 2.31.3
description: PostgreSQL (Postgres) is an open source object-relational database known for reliability and data integrity. ACID-compliant, it supports foreign keys, joins, views, triggers and stored procedures.
home: https://github.com/cowboysysop/charts/tree/master/charts/postgresql
icon: https://raw.githubusercontent.com/cowboysysop/charts/master/charts/postgresql/icon.png
keywords:
- postgresql
- postgres
- database
- sql
- replication
- cluster
maintainers:
- name: sebastien-prudhomme
  email: sebastien.prudhomme@gmail.com
name: postgresql
sources:
- https://github.com/cowboysysop/charts/tree/master/charts/postgresql
version: 16.0.0
