apiVersion: v2
appVersion: 0.9.0
description: Terminal and Web console for Kubernetes
home: https://github.com/astefanutti/kubebox
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: kubebox
version: 2.3.0
