apiVersion: v2
appVersion: 0.9.0
description: Terminal and Web console for Kubernetes
home: https://github.com/astefanutti/kubebox
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: kubebox
version: 2.5.0
dependencies:
  - name: common
    version: 1.6.1
    repository: https://charts.bitnami.com/bitnami/
