apiVersion: v2
appVersion: 0.9.0
description: Terminal and Web console for Kubernetes
home: https://github.com/astefanutti/kubebox
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: kubebox
sources:
  - https://github.com/astefanutti/kubebox
  - https://github.com/cowboysysop/charts/tree/master/charts/kubebox
version: 5.1.0
dependencies:
  - name: common
    version: 2.9.0
    repository: https://charts.bitnami.com/bitnami/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=1.24"
