apiVersion: v2
appVersion: 0.1.31
description: Kubernetes cluster visualiser and graphical explorer
home: https://github.com/benc-uk/kubeview
icon: https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/public/favicon.png
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: kubeview
sources:
  - https://github.com/benc-uk/kubeview
  - https://github.com/cowboysysop/charts/tree/master/charts/kubeview
version: 5.0.0
dependencies:
  - name: common
    version: 2.5.0
    repository: https://charts.bitnami.com/bitnami/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=1.24"
