apiVersion: v2
appVersion: 0.20.0
description: Creates diagrams from textual descriptions
home: https://kroki.io/
icon: https://raw.githubusercontent.com/yuzutech/kroki.io/master/assets/favicon-196x196.png
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: kroki
sources:
  - https://github.com/yuzutech/kroki
  - https://github.com/cowboysysop/charts/tree/master/charts/kroki
version: 2.1.0
dependencies:
  - name: common
    version: 2.2.4
    repository: https://charts.bitnami.com/bitnami/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=1.19"
