name: Lint and Test Charts

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm:
          - v3.1.3 # renovate: helm
          - v3.2.0 # renovate: helm
          - v3.3.0 # renovate: helm
          - v3.4.0 # renovate: helm
          - v3.5.0 # renovate: helm
          - v3.6.1 # renovate: helm
          - v3.7.0 # renovate: helm
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1.1
        with:
          version: ${{ matrix.helm }}

      - name: Set up Python
        uses: actions/setup-python@v2.2.0
        with:
          python-version: 3.7.5 # renovate: python

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml
        if: steps.list-changed.outputs.changed == 'true'
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes:
          - v1.16.15 # renovate: kindest/node
          - v1.17.17 # renovate: kindest/node
          - v1.18.19 # renovate: kindest/node
          - v1.19.11 # renovate: kindest/node
          - v1.20.7 # renovate: kindest/node
          - v1.21.2 # renovate: kindest/node
          - v1.22.0 # renovate: kindest/node
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0 # renovate: helm

      - name: Set up Python
        uses: actions/setup-python@v2.2.0
        with:
          python-version: 3.7.5 # renovate: python

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          node_image: kindest/node:${{ matrix.kubernetes }}

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.0
        with:
          fetch-depth: 0

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12.842.0
        with:
          config_file: checkov.yaml
