name: Lint and Test Charts

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm:
          - v3.1.3 # renovate: helm
          - v3.2.4 # renovate: helm
          - v3.3.4 # renovate: helm
          - v3.4.2 # renovate: helm
          - v3.5.4 # renovate: helm
          - v3.6.3 # renovate: helm
          - v3.7.2 # renovate: helm
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: ${{ matrix.helm }}

      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.11.4 # renovate: python

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml
        if: steps.list-changed.outputs.changed == 'true'
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes:
          - v1.19.16 # renovate: kindest/node
          - v1.20.15 # renovate: kindest/node
          - v1.21.14 # renovate: kindest/node
          - v1.22.17 # renovate: kindest/node
          - v1.23.17 # renovate: kindest/node
          - v1.24.15 # renovate: kindest/node
          - v1.25.11 # renovate: kindest/node
          - v1.26.6 # renovate: kindest/node
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.7.2 # renovate: helm

      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.11.4 # renovate: python

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: List excluded charts
        id: list-excluded
        run: |
          pip install semantic_version
          excluded=$(python .github/excluded-charts.py --kube-version ${{ matrix.kubernetes }})
          echo "excluded=$excluded" >> $GITHUB_OUTPUT

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml --excluded-charts "${{ steps.list-excluded.outputs.excluded }}")
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create kind cluster
        uses: helm/kind-action@v1.7.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          node_image: kindest/node:${{ matrix.kubernetes }}

      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.crds.yaml # renovate: cert-manager
          helm repo add jetstack https://charts.jetstack.io/
          helm install cert-manager jetstack/cert-manager -n cert-manager --create-namespace --version v1.6.1 --wait # renovate: cert-manager
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install Istio
        run: |
          helm repo add istio https://istio-release.storage.googleapis.com/charts/
          helm install istio-base istio/base -n istio-system --create-namespace --version v1.12.2 --wait # renovate: istio
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install Knative Serving
        run: |
          kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.2.0/serving-crds.yaml # renovate: knative-serving
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml --excluded-charts "${{ steps.list-excluded.outputs.excluded }}"
        if: steps.list-changed.outputs.changed == 'true'
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12.2407.0
        with:
          config_file: checkov.yaml
