name: Lint and Test Charts

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm:
          - v3.14.4 # renovate: helm
          - v3.15.4 # renovate: helm
          - v3.16.4 # renovate: helm
          - v3.17.4 # renovate: helm
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: ${{ matrix.helm }}

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.14.0 # renovate: python

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --config ct.yaml
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes:
          - v1.29.14 # renovate: kindest/node
          - v1.30.13 # renovate: kindest/node
          - v1.31.12 # renovate: kindest/node
          - v1.32.8 # renovate: kindest/node
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.3 # renovate: helm

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.14.0 # renovate: python

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: List excluded charts
        id: list-excluded
        run: |
          pip install semantic_version
          excluded=$(python .github/excluded-charts.py --kube-version ${{ matrix.kubernetes }})
          echo "excluded=$excluded" >> $GITHUB_OUTPUT

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml --excluded-charts "${{ steps.list-excluded.outputs.excluded }}")
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.13.0
        with:
          node_image: kindest/node:${{ matrix.kubernetes }}

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --config ct.yaml --excluded-charts "${{ steps.list-excluded.outputs.excluded }}"
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12.3022.0
        with:
          config_file: checkov.yaml
